[package]
name = "visor_corn"
version = "0.1.0"
authors = ["Colette ğŸŒ©ï¸â€ğŸ’ Kerr <Colette.m.y.Kerr@gmail.com>"]
edition = "2018"

[dependencies]
promissory = "0.1"
smol = { version = "1.2.5", optional = true }

[features]
test = ["smol"]
default = ["test"]